#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

$HOME/.config/polybar/launch.sh &

bspc config border_width         6
bspc config exclude class "virt-manager, Virt-manager"
bspc config window_gap           1
bspc config focused_border_color	"#7f849c"
bspc config normal_border_color		"#313244"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on

#Custom Section

feh -bg ~/Pictures/wallpapers/neon.jpg --bg-center

#From arch repo
#picom --config $HOME/.config/picom.conf 

#Xmobar (idk why i am doing this)
#xmobar
